version: "3"
services:
  api_test:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./database:/database
    entrypoint: >
      sh -c "sh /database/wait_for_mysql.sh
      && sh /database/clean_database.sh
      && sh /database/migrate.sh
      && sh /database/seed_test.sh
      && go test ./..."
    env_file:
      - backend/.env.test
    depends_on:
      - db_test

  db_test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - backend/.env.test
