version: "3"
services:
  api:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
      - ./database:/database
    ports:
      - 80:80
    env_file:
      - backend/.env
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - backend/.env
    ports:
      - 3306:3306

  frontend:
    build:
      context: web
      target: development
    volumes:
      - ./web:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    ports:
      - 9000:9000
    env_file:
      - web/.env

volumes:
  node_modules: