version: "3"
services:
  api:
    build:
      context: docker
    volumes:
      - ./src/ipo:/src
    working_dir: /src
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306