version: "3"
services:
  api_test:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    entrypoint: >
      sh -c "go test ./..."
    env_file:
      - backend/.env.test
    depends_on:
      - db_test

  db_test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - backend/.env.test
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
