version: "3"
services:
  api:
    build:
      context: docker
    volumes:
      - ./src/ipo:/src
    working_dir: /src
    ports:
      - "127.0.0.1:80:80"

#  mysql:
#    image: mysql:8
#    env_file:
#      - .env
#    volumes:
#      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
#    ports:
#      - "127.0.0.1:3306:3306"
#    restart: unless-stopped