version: "3"
services:
  api_test:
    build:
      context: docker
      target: test
    volumes:
      - ./src/ipo:/src
    working_dir: /src
    entrypoint: >
      sh -c "go test ./..."
    env_file:
      - src/ipo/.env.test
    depends_on:
      - db_test

  db_test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - src/ipo/.env.test
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
