version: 2
jobs:
  test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: make test
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: make build_prod

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master