version: 2
jobs:
  test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: make test
  build_and_push:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: make build_prod
      - run: make push_prod
  deploy_backend:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ce:bd:07:44:62:3f:fe:b6:6a:35:e5:68:ee:44:39:46"
      - run: make deploy_backend_prod
  deploy_web:
    docker:
      - image: circleci/node:12.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: make deploy_web_prod


workflows:
  version: 2
  test_build_push_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - build_and_push:
          context: theIPOguide-prod
          filters:
            branches:
              only: master
      - deploy_backend:
          context: theIPOguide-prod
          requires:
           - build_and_push
          filters:
            branches:
              only: master
      - deploy_web:
          context: theIPOguide-prod
          requires:
           - deploy_backend
          filters:
            branches:
              only: master