DROP TABLE IF EXISTS ipos;
DROP TABLE IF EXISTS companies;
DROP TABLE IF EXISTS markets;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS currencies;
DROP TABLE IF EXISTS industries;
DROP TABLE IF EXISTS sectors;
